// client/views/appReact/components/Nav.jsx
import React, { Component } from 'react';
import { Link } from 'react-router';

class Nav extends Component {
    render() {
        return (
            <div>
                <Link to="/">index</Link>&nbsp;&nbsp;&nbsp;
                <Link to="/about">about</Link>
            </div>
        );
    }
}

export default Nav;

// client/appVue/components/Nav.vue
<template>
  <div class="">
    <router-link to="/">首页</router-link> &nbsp;&nbsp;&nbsp;
    <router-link to="/list">列表</router-link>
  </div>
</template>
<script>
/**
 * 版权信息
 */
export default {
  name: 'index',
  data() {
    return {
    }
  },
  created(){
  },

  props: [],

  components: {

  },

  computed: {

  },

  methods: {
  }
}
</script>

<style scoped>

</style>
